# This file was automatically generated by SWIG
package Image::Filter::Emboss;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
@EXPORT_OK = qw(emboss);
package Image::Filter::Emboss;
bootstrap Image::Filter::Emboss;
1;
__END__