# This file was automatically generated by SWIG
package Image::Filter::Foo;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
@EXPORT_OK = qw(foo);
package Image::Filter::Foo;
bootstrap Image::Filter::Foo;
1;
__END__